config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts do
    get 'checkout' , to:'carts#checkout'
    post 'checkout' , to:'carts#checkout'
    get 'purchase_complete' , to:'carts#purchase_complete'
  end
  resources :stores
  get 'cart/empty' , to:'carts#empty'
  
  get 'admin/login_admin'
  post 'admin/login_admin'
  get 'admin/logout_admin'
  get 'admin/dashboard'
  get 'home/index'
  get 'home/mobile_gallery'
  get 'home/search_results'
  devise_for :users

  root 'home#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_one_attached :product_image
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: %i[ show edit update destroy ]
  before_action :admin_logged_in


  def admin_logged_in
    if session[:admin].nil?
      flash[:notice] = "Please Login as Admin first to access the Dashboard"
      redirect_to :controller=>:admin, :action=>:login_admin
    end
  end


  # GET /stores or /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html #looks for views/stores/index.html.erb
      format.js   #looks for views/stores/index.js.erb
    end
  end

  # GET /stores/1 or /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores or /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: "Store was successfully created." }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1 or /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: "Store was successfully updated." }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1 or /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: "Store was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def store_params
      params.require(:store).permit(:product_image,:product_name, :product_type, :brand, :color, :configuration, :description, :launch_year, :mrp, :sell_price)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<div class="container">
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% if store.product_image.attached? %>
         <%= image_tag(store.product_image, width: "75px", height: "75px") %>
            <% else %>
        <%= image_tag("logo_smart.png", alt: "No product image", width: "75px", height: "75px") %>
     <% end %>
  <div class="form-group">
    <%= form.label :product_image %>
    <%= form.file_field :product_image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :product_name %>
    <%= form.text_field :product_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :product_type %>
    <%= form.text_field :product_type, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :brand %>
    <%= form.text_field :brand , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :color %>
    <%= form.text_field :color , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :configuration %>
    <%= form.text_field :configuration, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :launch_year %>
    <%= form.number_field :launch_year, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :mrp %>
    <%= form.text_field :mrp , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :sell_price %>
    <%= form.text_field :sell_price, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Add Product", class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/stores/_stores.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h3>My Store</h3>
<br/>
<table class="table table-striped">
  <thead>
    <tr>
    <th>PID</th>
    <th>Product Image</th>
      <th>Product name</th>
      <th>Product type</th>
      <th>Brand</th>
      <th>Color</th>
      <th>Configuration</th>
      <th>Description</th>
      <th>Launch year</th>
      <th>Mrp</th>
      <th>Sell price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
       <td><%= store.id %></td>
        <td class="input-field col s6 m6">
            <% if store.product_image.attached? %>
         <%= image_tag(store.product_image, width: "75px", height: "75px") %>
            <% else %>
        <%= image_tag("logo_smart.png", alt: "No product image", width: "75px", height: "75px") %>
            <% end %>
        </td>
        <td><%= store.product_name %></td>
        <td><%= store.product_type %></td>
        <td><%= store.brand %></td>
        <td><%= store.color %></td>
        <td><%= store.configuration %></td>
        <td><%= store.description %></td>
        <td><%= store.launch_year %></td>
        <td><%= store.mrp %></td>
        <td><%= store.sell_price %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_store_path, class: "btn btn-default" %>
</div>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product type</th>
      <th>Brand</th>
      <th>Color</th>
      <th>Configuration</th>
      <th>Description</th>
      <th>Launch year</th>
      <th>Mrp</th>
      <th>Sell price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.product_name %></td>
        <td><%= store.product_type %></td>
        <td><%= store.brand %></td>
        <td><%= store.color %></td>
        <td><%= store.configuration %></td>
        <td><%= store.description %></td>
        <td><%= store.launch_year %></td>
        <td><%= store.mrp %></td>
        <td><%= store.sell_price %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_store_path %>

app/views/stores/index.js.erb
$(".myBoard").html("<%= j (render 'stores') %>");

app/views/stores/new.html.erb
<%= link_to '<i class="bi bi-arrow-left"></i>Return to Dashboard'.html_safe, admin_dashboard_path, class: "btn btn-danger", style: "color:white" %>
<br/><br/><br/>
<h1>New Store</h1>

<%= render 'form', store: @store %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @store.product_name %>
</p>

<p>
  <strong>Product type:</strong>
  <%= @store.product_type %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @store.brand %>
</p>

<p>
  <strong>Color:</strong>
  <%= @store.color %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @store.configuration %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>Launch year:</strong>
  <%= @store.launch_year %>
</p>

<p>
  <strong>Mrp:</strong>
  <%= @store.mrp %>
</p>

<p>
  <strong>Sell price:</strong>
  <%= @store.sell_price %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>