config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts do
    get 'checkout' , to:'carts#checkout'
    post 'checkout' , to:'carts#checkout'
    get 'purchase_complete' , to:'carts#purchase_complete'
  end
  resources :stores
  get 'cart/empty' , to:'carts#empty'
  
  get 'admin/login_admin'
  post 'admin/login_admin'
  get 'admin/logout_admin'
  get 'admin/dashboard'
  get 'home/index'
  get 'home/mobile_gallery'
  get 'home/search_results'
  devise_for :users

  root 'home#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def mobile_gallery
    @stores = Store.all
  end
  
  def search_results
    keyword="%" + params[:search_keyword].to_s + "%"
    @stores = Store.find_by_sql ["Select * from stores WHERE product_name like ? or product_type like ? or brand like ? or color like ? or description like ?",keyword,keyword,keyword,keyword,keyword]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_card_mobile.html.erb
<div class="container">
	<div class="row justify-content-center  align-items-center">
		<% count=0 %>
		<%  @stores.each do |store| %>
	<% if (count%4) == 0 %>
	</div>
	<br/><br/><br/>
	<div class="row justify-content-center  align-items-center">
	<%end%>
	<% count+=1%>
	
	<div class="col col-sm-3 col-md-3">

		<div class="card" style="min-height:590px;">
			<%= image_tag(store.product_image ,height:"300px",width:"50px", class:"card-img-top") %>
			
			<div class="card-body">
				<big class="card-title"><%=store.product_name%></big>
				<h4 class="card-text"><%=store.configuration%></h4>
				<br/>
				<p class="card-text text-danger"><strike>&#8377;<%=store.mrp%></strike></p>
				<h3 class="card-text text-warning">&#8377;<%=store.sell_price%></h3>
			
			</div>
			
			<div class="card-body">
			<%= button_to 'Add to Cart', cart_items_path(:store_id => store.id), class:"btn btn-warning",style:"color:white" %> 
			
			</div>
		</div>
	</div>
	
<% end %>
</div>

app/views/home/mobile_gallery.html.erb
		
		<!--try top banner main wrapper End-->
		<div class="main-header">
			<div class="container">
				<div class="row">
					<!-- Main Box -->
					
					<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
						<div class="try_logo_wrapper">
							<a href="/home/index" style="background-color: transparent">
								<img src="/assets/logo_smart.png" alt="logo" height="60px" width="100px">
							</a>
						</div>
					</div>
					<div class="col-lg-10 col-md-10 col-sm-10 col-xs-12">
						<div class="main-box">
							<div class="main-box">
								<div class="auto-container">
									<div class="outer-container clearfix">
										<!--Logo Box-->
										<!--Nav Outer-->
										<div class="nav-outer clearfix">
											<!-- Main Menu -->
											<nav class="main-menu">
												<div class="navbar-header">
													<!-- Toggle Button -->
													<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span>
														<span class="icon-bar"></span>
														<span class="icon-bar"></span>
													</button>
												</div>
												<div class="navbar-collapse collapse scroll-nav clearfix">
													<ul class="navigation clearfix">
														<li><a href="/home/index">Home</a>
														</li>
														<li><a href="/home/mobile_gallery">Mobile</a>
														</li>
														<li><a href="#"><i class="material-icons">favorite</i></a></li>
														<% if session[:cart_id].nil? %>
															<li><a href="/cart/empty"><i class="material-icons">shopping_cart</i></a></li>
														<% else %>
															<li><%= link_to '<i class="material-icons">shopping_cart</i>'.html_safe, cart_path(:id=> session[:cart_id]) %></li>
															
														<% end %>
													
														<li><a href="#"><i class="material-icons">card_travel</i></a></li>
														<li><a href="/users/edit"><i class="material-icons">person</i></a></li>

														<li><a href="/admin/login_admin" style="float:right">Admin</a></li>

										
													</ul>
												</div>
											</nav>
											<!-- Main Menu End-->
										</div>
										<!--Nav Outer End-->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
<br/><br/>

<div class="container">
	<div class="row justify-content-center  align-items-center">
		<% count=0 %>
		<%  @stores.each do |store| %>
	<% if (count%4) == 0 %>
	</div>
	<br/><br/><br/>
	<div class="row justify-content-center  align-items-center">
	<%end%>
	<% count+=1%>
	
	<div class="col col-sm-3 col-md-3">

		<div class="card" style="min-height:590px;">
			<%= image_tag(store.product_image ,height:"300px",width:"50px", class:"card-img-top") %>
			
			<div class="card-body">
				<big class="card-title"><%=store.product_name%></big>
				<h4 class="card-text"><%=store.configuration%></h4>
				<br/>
				<p class="card-text text-danger"><strike>&#8377;<%=store.mrp%></strike></p>
				<h3 class="card-text text-warning">&#8377;<%=store.sell_price%></h3>
			
			</div>
			
			<div class="card-body">
			<%= button_to 'Add to Cart', cart_items_path(:store_id => store.id), class:"btn btn-warning",style:"color:white" %> 
			
			</div>
		</div>
	</div>
	
<% end %>
</div>
</div>

  

app/views/home/search_results.html.erb
		
		<!--try top banner main wrapper End-->
		<div class="main-header">
			<div class="container">
				<div class="row">
					<!-- Main Box -->
					
					<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
						<div class="try_logo_wrapper">
							<a href="/home/index" style="background-color: transparent">
								<img src="/assets/logo_smart.png" alt="logo" height="60px" width="100px">
							</a>
						</div>
						
					</div>
					
					<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
						<div class="main-box">
							<div class="main-box">
								<div class="auto-container">
									<div class="outer-container clearfix">
										<!--Logo Box-->
										<!--Nav Outer-->
										<div class="nav-outer clearfix">
											<!-- Main Menu -->
											<nav class="main-menu">
												<div class="navbar-header">
													<!-- Toggle Button -->
													<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="icon-bar"></span>
														<span class="icon-bar"></span>
														<span class="icon-bar"></span>
													</button>
												</div>
												<div class="navbar-collapse collapse scroll-nav clearfix">
													<ul class="navigation clearfix">
														<li><a href="/home/index">Home</a>
														</li>
														<li><a href="/home/mobile_gallery">Mobile</a>
														</li>
														
														<li><a href="#"><i class="material-icons">favorite</i></a></li>
														<% if session[:cart_id].nil? %>
															<li><a href="/cart/empty"><i class="material-icons">shopping_cart</i></a></li>
														<% else %>
															<li><%= link_to '<i class="material-icons">shopping_cart</i>'.html_safe, cart_path(:id=> session[:cart_id]) %></li>
															
														<% end %>
													
														<li><a href="#"><i class="material-icons">card_travel</i></a></li>
														<li><a href="/users/edit"><i class="material-icons">person</i></a></li>

														<li><a href="/admin/login_admin" style="float:right">Admin</a></li>
														
															
														
													</ul>
												</div>
											</nav>
											<!-- Main Menu End-->
										</div>
										<!--Nav Outer End-->
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
<br/><br/>
<div class="row">
<div class="col col-sm-3 col-md-3" style="float:right;right:18%">
<div class="" id="searchMobiles">
		<%= form_with url: "/home/search_results", method: :get , local: true do |f| %>
			<div class="row">
			<div class="col col-sm-11 col-md-11">
			<%= f.text_field :search_keyword , class:"form-control", placeholder:"Enter Keyword to Search..." %>
			</div>
			<div class="col col-sm-1 col-md-1">
			<%= f.button :submit , class: "btn btn-success" do  %>
				<i class='bi bi-search' ></i>
			<% end %>
			</div>
			</div>
		<% end %>
</div>
</div>
</div>
<%= render 'card_mobile'%>
</div>

  