config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  resources :carts do
    get 'checkout' , to:'carts#checkout'
    post 'checkout' , to:'carts#checkout'
    get 'purchase_complete' , to:'carts#purchase_complete'
  end
  resources :stores
  get 'cart/empty' , to:'carts#empty'
  
  get 'admin/login_admin'
  post 'admin/login_admin'
  get 'admin/logout_admin'
  get 'admin/dashboard'
  get 'home/index'
  get 'home/mobile_gallery'
  get 'home/search_results'
  devise_for :users

  root 'home#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, :dependent => :destroy

    def add_product(store_id)
        current_item = cart_items.find_by_store_id(store_id)
        if current_item
            current_item.quantity += 1
        else
            current_item = cart_items.build(:store_id => store_id)
        end
        current_item
    end
    
    def total_price
        cart_items.to_a.sum { |item| item.total_price }
    end 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[ show edit update destroy ]
  require "active_merchant/billing/rails"
  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  def empty
  end

  def purchase_complete
  end
  
  def checkout
    
  	if request.post?

      amount = session[:amount]
  ActiveMerchant::Billing::Base.mode = :test
  
  # Create a new credit card object
  credit_card = ActiveMerchant::Billing::CreditCard.new(
    :number     => params[:cardnumber],
    :month      => params[:month],
    :year       => params[:year],
    :first_name => params[:cardname],
    :last_name  => params[:cardname],
    :verification_value  => params[:cvv]
  )
  
  
  if credit_card.valid?
    # Create a gateway object to the TrustCommerce service
    gateway = ActiveMerchant::Billing::TrustCommerceGateway.new(
      :login    => 'TestMerchant',
      :password => 'password'
    )
  
  
  
    # Authorize for $10 dollars (1000 cents)
    response = gateway.authorize(amount.to_i, credit_card)
  
    if response.success?
      # Capture the money
      #Triger the mailer
      session[:cart]=nil
      gateway.capture(amount.to_i, response.authorization)
      redirect_to :action=>:purchase_complete
    end
    else
      flash[:notice] = "Invalid credit card. Give proper inputs"
      render :action=>:checkout
    end
   end
  end
  # GET /carts/1 or /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
      rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to @cart, :notice => 'Invalid Cart'
      else
        respond_to do |format|
          format.html # show.html.erb
        end
      end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div class="container">
<% unless cart.cart_items.empty? %>
<h2>Your Cart</h2>
<table class="table table-borderless table-hover">
	<%= render(cart.cart_items) %>
	<tr>
		<td colspan="4">Total</td>
		<td class="total_cell"><%= number_to_indian_currency(cart.total_price)  %></td>
	</tr>
</table>
<% session[:amount] = cart.total_price %>
<%= button_to 'Empty Cart', cart, :method => :delete, :confirm => 'Are you sure?', class: "btn btn-danger" %>
<br/>
	<%= link_to "Continue Shopping", "home/mobile_gallery" , class: "btn btn-warning", style: "color:white" %> 
	<% if user_signed_in? && !session[:cart_id].nil?%>
<%= link_to "Checkout" ,session[:cart_id].to_s + "/checkout" , class: "btn btn-primary", style: "color:white;float:right"%>
	<% else %>
	<%= link_to "Login To Checkout", new_user_session_path, class: "btn btn-primary", style: "color:white;float:right"%>
	<% end %>

<% end %>
</div>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/checkout.html.erb
<%= form_with do |form| %>


 

<div id="myCheckout">
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="bi bi-person-circle"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe">
            <label for="email"><i class="bi bi-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="john@example.com">
            <label for="adr"><i class="bi bi-house"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="bi bi-signpost"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
         
           
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum"><i class="bi bi-credit-card"></i>Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
           <%= form.label :date_of_expiry %>
            <select name="month" id="check_out_month">
                <option selected value="01">Janurary 
                <option  value="02">Feburary
                <option  value="03">March
                <option  value="04">April 
                <option  value="05">May 
                <option  value="06">June 
                <option  value="07">July 
                <option  value="08">August 
                <option  value="09">September 
                <option  value="10">October 
                <option  value="11">November 
                <option  value="12">December 
                </select>
                <select name="year" id=check_out_year">
    
                <option  value="2021">2021
                <option  value="2022">2022
                <option  value="2023">2023
                <option  value="2024">2024
                <option  value="2025">2025
                <option  value="2026">2026
                <option  value="2027">2027
                <option  value="2028">2028
                <option  value="2029">2029
            </select>
            <br/><br/>
            <div class="row">
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
               
      </form>
    </div>
  </div>
    
  <div class="col-25">
    <div class="container">
      <h4>Cart</h4>
     
      <hr>
      <p>Total <span class="price" style="color:black"><b> Rs.<%= session[:amount] %></b></span></p>

       <%= form.submit "Proceed to Pay", class: "btn btn-primary" %>
    </div>
  </div>
</div>
</div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/empty.html.erb
<div class="container">
<h1>Cart</h1>
<h4>Your Cart is Empty!</h4>
<br/>
<p>Add Products to the cart by exploring our range of products by clicking on the following link.</p>
<br/><br/>
<big>Click on the link</big>
<br/>
<%= link_to "Mobiles Gallery", "home/mobile_gallery", class: "btn btn-primary" , style: "color:white" %>
</div>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/purchase_complete.html.erb
Thank you for shopping with us!<br />
	
your order has been processed.<br />

A detailed email has been sent.<br />

<a class="btn btn-default" href="/home/index">Click here to continue the shopping</a>

app/views/carts/show.html.erb
<%= render @cart %>